### ISSUE TITLE
Question about CREA's data engineer

### ISSUE THREAD

**Issue by bangyuwen** [energyandcleanair/creadeweather#1]
Hi @hubert-thieriot , 

I just saw the job description of CREA [data engineer](https://energyandcleanair.org/jobs/data-engineer/)
It requires Python skills for the job and R as a bonus. But I saw a lot more programs written in R.
So I have a question about the skills requirements. Which would be the main programming language?

Thanks,
Wayne

**Comment by hubert-thieriot** [comment]
Hi Bang YuWen,

Apologies, I missed your question... Unfortunately, the position has long been filed.

All the best,

Hubert
